### ISSUE TITLE
Add inotify-tools for Linux/Phoenix

### ISSUE THREAD

**Issue by khionu** [shanesveller/nix-beam-overlay#3]
As on the tin, it would be great if the flake added inotify-tools for reloading on changes.

**Comment by shanesveller** [comment]
@khionu You're quite right, I'll add this soon - in the meantime you can temporarily use this as an escape hatch:

```nix
beamWorkspace.devShell.extraPackages = lib.optional pkgs.stdenv.isLinux pkgs.inotify-tools;
```

**Comment by khionu** [comment]
Thanks!
